In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import ydata_profiling as yp

c:\Users\DELL\Desktop\ML Projects\Customer_Segmentation\customer\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
data = pd.read_excel(r"../data/raw/online_retail.csv")
df = pd.DataFrame(data)
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[ns]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 32.1+ MB

### Look for quantity has value negative and price

In [4]:
df.describe()

,Quantity,InvoiceDate,Price,Customer ID
count,525461.000000,525461,525461.000000,417534.000000
mean,10.337667,2010-06-28 11:37:36.845017856,4.688834,15360.645478
min,-9600.000000,2009-12-01 07:45:00,-53594.360000,12346.000000
25%,1.000000,2010-03-21 12:20:00,1.250000,13983.000000
50%,3.000000,2010-07-06 09:51:00,2.100000,15311.000000
75%,10.000000,2010-10-15 12:45:00,4.210000,16799.000000
max,19152.000000,2010-12-09 20:01:00,25111.090000,18287.000000
std,107.424110,NaN,146.126914,1680.811316

In [ ]:
df.describe(include='object')

        Invoice StockCode                         Description         Country
count    525461    525461                              522533          525461
unique    28816      4632                                4681              40
top      537434    85123A  WHITE HANGING HEART T-LIGHT HOLDER  United Kingdom
freq        675      3516                                3549          485852

In [5]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

In [6]:
df.drop(columns=['Description'], inplace=True)

In [7]:
df[df["Customer ID"].isnull()]

,Invoice,StockCode,Quantity,InvoiceDate,Price,Customer ID,Country
263,489464,21733,-96,2009-12-01 10:52:00,0.00,NaN,United Kingdom
283,489463,71477,-240,2009-12-01 10:52:00,0.00,NaN,United Kingdom
284,489467,85123A,-192,2009-12-01 10:53:00,0.00,NaN,United Kingdom
470,489521,21646,-50,2009-12-01 11:44:00,0.00,NaN,United Kingdom
577,489525,85226C,1,2009-12-01 11:49:00,0.55,NaN,United Kingdom
...,...,...,...,...,...,...,...
525231,538159,21324,-18,2010-12-09 17:17:00,0.00,NaN,United Kingdom
525232,538158,20892,-32,2010-12-09 17:17:00,0.00,NaN,United Kingdom
525233,538160,20956,288,2010-12-09 17:18:00,0.00,NaN,United Kingdom
525234,538161,46000S,-100,2010-12-09 17:25:00,0.00,NaN,United Kingdom
525235,538162,46000M,-100,2010-12-09 17:25:00,0.00,NaN,United Kingdom

### This is not a valid transaction, so we can drop null

In [8]:
df.dropna(subset=["Customer ID"], inplace=True)

In [ ]:
profile = yp.ProfileReport(df, title="Customer Segmentation EDA Report")
profile.to_file("../reports/Customer_Segmentation_EDA_Report.html")

100%|██████████| 7/7 [00:00<00:00,  7.45it/s]03<00:03,  1.81it/s, Describe variable: Country]
Summarize dataset: 100%|██████████| 25/25 [00:11<00:00,  2.17it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:02<00:00,  2.89s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  4.05it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 103.15it/s]

In [9]:
df['Customer ID'].nunique()

4383

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 417534 entries, 0 to 525460
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      417534 non-null  object
 1   StockCode    417534 non-null  object
 2   Quantity     417534 non-null  int64
 3   InvoiceDate  417534 non-null  datetime64[ns]
 4   Price        417534 non-null  float64
 5   Customer ID  417534 non-null  float64
 6   Country      417534 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 25.5+ MB

In [102]:
df.StockCode.nunique()

4031

### Clean StockCode by removing trailing letters and check unique values again

In [10]:
df["StockCode_clean"] = df["StockCode"].astype(str).str.replace(
    r"[A-Za-z]$", 
    "", 
    regex=True
)
df["StockCode_clean"].nunique()

3286

In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 417534 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Invoice          417534 non-null  object
 1   StockCode        417534 non-null  object
 2   Quantity         417534 non-null  int64
 3   InvoiceDate      417534 non-null  datetime64[ns]
 4   Price            417534 non-null  float64
 5   Customer ID      417534 non-null  float64
 6   Country          417534 non-null  object
 7   StockCode_clean  417534 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 28.7+ MB

In [11]:
(
    df.groupby("StockCode_clean")["StockCode"]
      .nunique()
      .sort_values(ascending=False)
      .head(10)
)

StockCode_clean
90214    24
16169     9
84596     8
84247     8
85049     8
85230     7
47503     7
84509     6
17011     6
17012     6
Name: StockCode, dtype: int64

In [12]:
df.loc[
    ~df["StockCode_clean"].astype(str).str.isnumeric(),
    "StockCode_clean"
].unique()

array(['POS', '79323L', '15056B', '', '79323G', 'C2', 'BANK CHARGE',
       'TEST001', 'TEST002', 'PAD', 'ADJUS', 'ADJUST2', 'SP1002'],
      dtype=object)

### Remove invalid stock codes

In [13]:
invalid_stock_codes = df.loc[
    ~df["StockCode_clean"].astype(str).str.isnumeric(),
    "StockCode_clean"
].unique()
df = df.loc[~df["StockCode_clean"].isin(invalid_stock_codes)]
df["StockCode_clean"] = df["StockCode_clean"].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 414831 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Invoice          414831 non-null  object
 1   StockCode        414831 non-null  object
 2   Quantity         414831 non-null  int64
 3   InvoiceDate      414831 non-null  datetime64[ns]
 4   Price            414831 non-null  float64
 5   Customer ID      414831 non-null  float64
 6   Country          414831 non-null  object
 7   StockCode_clean  414831 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(2), object(3)
memory usage: 28.5+ MB

In [14]:
df.drop(columns=["StockCode"], inplace=True)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 414831 entries, 0 to 525460
Data columns (total 7 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Invoice          414831 non-null  object
 1   Quantity         414831 non-null  int64
 2   InvoiceDate      414831 non-null  datetime64[ns]
 3   Price            414831 non-null  float64
 4   Customer ID      414831 non-null  float64
 5   Country          414831 non-null  object
 6   StockCode_clean  414831 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(2), object(2)
memory usage: 25.3+ MB

In [16]:
df.describe()

,Quantity,InvoiceDate,Price,Customer ID,StockCode_clean
count,414831.000000,414831,414831.000000,414831.000000,414831.000000
mean,12.818225,2010-07-01 04:22:54.343382784,3.024750,15365.849295,35364.773758
min,-9360.000000,2009-12-01 07:45:00,0.000000,12346.000000,10002.000000
25%,2.000000,2010-03-26 13:05:00,1.250000,13993.000000,21621.000000
50%,5.000000,2010-07-09 09:46:00,1.950000,15311.000000,22322.000000
75%,12.000000,2010-10-14 15:45:00,3.750000,16805.000000,35648.000000
max,19152.000000,2010-12-09 20:01:00,295.000000,18287.000000,90214.000000
std,101.520227,NaN,4.475279,1678.287726,24765.865133

### Remove rows with negative Quantity or Price

In [17]:
df = df[(df["Quantity"] > 0) & (df["Price"] > 0)]

In [114]:
df.describe()

,Quantity,InvoiceDate,Price,Customer ID,StockCode_clean
count,405513.000000,405513,405513.000000,405513.000000,405513.000000
mean,13.623282,2010-07-01 12:44:56.709205760,2.986046,15373.393356,35308.806655
min,1.000000,2009-12-01 07:45:00,0.030000,12346.000000,10002.000000
25%,2.000000,2010-03-26 14:29:00,1.250000,14004.000000,21621.000000
50%,5.000000,2010-07-11 10:28:00,1.950000,15326.000000,22321.000000
75%,12.000000,2010-10-14 17:23:00,3.750000,16814.000000,35594.000000
max,19152.000000,2010-12-09 20:01:00,295.000000,18287.000000,90214.000000
std,97.075488,NaN,4.288060,1677.215464,24732.059600

### Check Remove or no

In [19]:
df[
    (df["Quantity"] <= 0) |
    (df["Price"] <= 0)
].shape

(0, 7)

### Make some Feature Engineering

In [ ]:
df["TotalPrice"] = df["Quantity"] * df["Price"]

In [117]:
df

,Invoice,Quantity,InvoiceDate,Price,Customer ID,Country,StockCode_clean,TotalPrice
0,489434,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,85048,83.40
1,489434,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,79323,81.00
2,489434,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,79323,81.00
3,489434,48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,22041,100.80
4,489434,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,21232,30.00
...,...,...,...,...,...,...,...,...
525456,538171,2,2010-12-09 20:01:00,2.95,17530.0,United Kingdom,22271,5.90
525457,538171,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom,22750,3.75
525458,538171,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom,22751,3.75
525459,538171,2,2010-12-09 20:01:00,3.75,17530.0,United Kingdom,20970,7.50
525460,538171,2,2010-12-09 20:01:00,1.95,17530.0,United Kingdom,21931,3.90

In [21]:
invoice_basket = (
    df.groupby("Invoice")["StockCode_clean"]
      .nunique()
      .reset_index(name="BasketSize")
)
invoice_basket

       Invoice  BasketSize
0       489434           7
1       489435           4
2       489436          18
3       489437          23
4       489438          12
...        ...         ...
18961   538167          25
18962   538168          29
18963   538169          13
18964   538170          24
18965   538171          64

[18966 rows x 2 columns]

In [22]:
reference_date = df["InvoiceDate"].max() + pd.Timedelta(days=1)

In [ ]:
rfm = df.groupby("Customer ID").agg({
    "InvoiceDate": lambda x: (reference_date - x.max()).days,  
    "Invoice": "nunique",                                       
    "TotalPrice": "sum"                                         
}).reset_index()

rfm.columns = ["CustomerID", "Recency", "Frequency", "Monetary"]

In [24]:
rfm

      CustomerID  Recency  Frequency  Monetary
0        12346.0      165          2    163.41
1        12347.0        3          2   1323.32
2        12348.0       74          1    221.16
3        12349.0       43          2   2221.14
4        12351.0       11          1    300.93
...          ...      ...        ...       ...
4280     18283.0       18          6    641.77
4281     18284.0       67          1    411.68
4282     18285.0      296          1    377.00
4283     18286.0      112          2   1246.43
4284     18287.0       18          4   2295.71

[4285 rows x 4 columns]

In [122]:
df["Customer ID"].nunique()

4285

In [123]:
df[df["Customer ID"] == 12348.0]

,Invoice,Quantity,InvoiceDate,Price,Customer ID,Country,StockCode_clean,TotalPrice
358167,524140,24,2010-09-27 14:59:00,0.55,12348.0,Finland,21213,13.20
358168,524140,24,2010-09-27 14:59:00,0.55,12348.0,Finland,84991,13.20
358169,524140,24,2010-09-27 14:59:00,0.55,12348.0,Finland,22951,13.20
358170,524140,24,2010-09-27 14:59:00,0.55,12348.0,Finland,84992,13.20
358171,524140,24,2010-09-27 14:59:00,0.55,12348.0,Finland,21977,13.20
358172,524140,12,2010-09-27 14:59:00,1.45,12348.0,Finland,84988,17.40
358173,524140,12,2010-09-27 14:59:00,1.45,12348.0,Finland,84987,17.40
358174,524140,12,2010-09-27 14:59:00,1.45,12348.0,Finland,21211,17.40
358175,524140,12,2010-09-27 14:59:00,0.85,12348.0,Finland,21723,10.20
358176,524140,12,2010-09-27 14:59:00,0.85,12348.0,Finland,21725,10.20
358177,524140,12,2010-09-27 14:59:00,0.85,12348.0,Finland,21726,10.20
358178,524140,24,2010-09-27 14:59:00,0.29,12348.0,Finland,21985,6.96
358179,524140,24,2010-09-27 14:59:00,0.29,12348.0,Finland,21980,6.96
358180,524140,24,2010-09-27 14:59:00,0.29,12348.0,Finland,21983,6.96
358181,524140,24,2010-09-27 14:59:00,0.29,12348.0,Finland,21981,6.96
358182,524140,24,2010-09-27 14:59:00,0.55,12348.0,Finland,22952,13.20
358183,524140,12,2010-09-27 14:59:00,1.45,12348.0,Finland,22950,17.40
358185,524140,24,2010-09-27 14:59:00,0.29,12348.0,Finland,21967,6.96
358186,524140,24,2010-09-27 14:59:00,0.29,12348.0,Finland,21982,6.96

In [25]:
rfm["AvgOrderValue"] = rfm["Monetary"] / rfm["Frequency"]

In [26]:
rfm

      CustomerID  Recency  Frequency  Monetary  AvgOrderValue
0        12346.0      165          2    163.41      81.705000
1        12347.0        3          2   1323.32     661.660000
2        12348.0       74          1    221.16     221.160000
3        12349.0       43          2   2221.14    1110.570000
4        12351.0       11          1    300.93     300.930000
...          ...      ...        ...       ...            ...
4280     18283.0       18          6    641.77     106.961667
4281     18284.0       67          1    411.68     411.680000
4282     18285.0      296          1    377.00     377.000000
4283     18286.0      112          2   1246.43     623.215000
4284     18287.0       18          4   2295.71     573.927500

[4285 rows x 5 columns]

In [27]:
rfm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4285 entries, 0 to 4284
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CustomerID     4285 non-null   float64
 1   Recency        4285 non-null   int64
 2   Frequency      4285 non-null   int64
 3   Monetary       4285 non-null   float64
 4   AvgOrderValue  4285 non-null   float64
dtypes: float64(3), int64(2)
memory usage: 167.5 KB

In [ ]:
rfm_profile = yp.ProfileReport(rfm, title="RFM Data EDA Report")
rfm_profile.to_file("../reports/RFM_Data_Report.html")

100%|██████████| 5/5 [00:00<00:00, 370.14it/s]0<?, ?it/s, Describe variable: AvgOrderValue]
Summarize dataset: 100%|██████████| 39/39 [00:02<00:00, 14.32it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:01<00:00,  1.47s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  3.47it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 121.77it/s]

In [ ]:
rfm.to_csv("../data/processed/rfm_data.csv", index=False)